var a=5,mod;
document.write("value after variable declaration is undefined: <br>");
document.write("initial value :"+a+"<br>");
a++;
document.write("value after increment is: "+a+"<br>");
a=a+7;
document.write("value after addition of 7 is:"+a+"<br>");
a=a-1;
document.write("value after decrement of variable is:"+a+"<br>");
mod=a%3;
document.write("output:the remainder is:"+mod);